export const mockExchangerData = {
  date: "01.12.2014",
  bank: "PB",
  baseCurrency: 980,
  baseCurrencyLit: "UAH",
  exchangeRate: [
      {
          baseCurrency: "UAH",
          currency: "CHF",
          saleRateNB: 15.638975,
          purchaseRateNB: 15.638975,
          saleRate: 17.0,
          purchaseRate: 15.5,
      },
      {
          baseCurrency: "UAH",
          currency: "EUR",
          saleRateNB: 37.2,
          purchaseRateNB: 38.1,
          saleRate: 42.2,
          purchaseRate: 41.1,
      },
      {
          baseCurrency: "UAH",
          currency: "GBP",
          saleRateNB: 23.632491,
          purchaseRateNB: 23.632491,
          saleRate: 25.8,
          purchaseRate: 24.0,
      },
      {
          baseCurrency: "UAH",
          currency: "PLZ",
          saleRateNB: 4.492201,
          purchaseRateNB: 4.492201,
          saleRate: 5.0,
          purchaseRate: 4.2,
      },
      {
          baseCurrency: "UAH",
          currency: "SEK",
          saleRateNB: 2.028375,
          purchaseRateNB: 2.028375, 
          saleRate: 2.4,
          purchaseRate: 2.2,
      },
      {
          baseCurrency: "UAH",
          currency: "UAH",
          saleRateNB: 1.0,
          purchaseRateNB: 1.0,
          saleRate: 1.0,
          purchaseRate: 1.0,
      },
      {
          baseCurrency: "UAH",
          currency: "USD",
          saleRateNB: 36.68,
          purchaseRateNB: 36.9,
          saleRate: 40.4,
          purchaseRate: 40.3,
      },
      {
          baseCurrency: "UAH",
          currency: "XAU",
          saleRateNB: 17747.747,
          purchaseRateNB: 17747.747,
          saleRate: 17747.747,
          purchaseRate: 17747.747,
      },
      {
          baseCurrency: "UAH",
          currency: "CAD",
          saleRateNB: 13.21074,
          purchaseRateNB: 13.21074,
          saleRate: 15.0,
          purchaseRate: 13.0,
      },
  ],
};
